config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet', as: 'retweets'
  end

  resources :retweets
  resources :likes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
	has_many :likes
	has_many :retweets
	validates :content, presence: true 
	enum status: [:draft, :published]
	paginates_per 50 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets
         has_many :likes
         has_many :retweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image_url])
  end
   
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_tweet, only: [:show, :edit,:update,:destroy, :complete]
  
  def new
    @like= Like.new
  end
  
  def create
    tweet =Tweet.find_by(id:params[:format])
    if Like.find_by(user_id:current_user.id,tweet_id:tweet.id )
      @destruir= Like.find_by(user_id:current_user.id,tweet_id:tweet.id)
      @destruir.destroy
      tweet.likes_count-=1
      tweet.save
      redirect_to root_path
    else
      Like.create(user_id:current_user.id, tweet_id:tweet.id)
      tweet.likes_count+=1
      tweet.save
      redirect_to root_path
    end
  end

  def destroy
  end

private

  def like_params
    params.require(:like).permit(:user_id,:tweet_id)
  end
  
  def set_like
    @like = Like.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @tweets = Tweet.order("created_at DESC").page params[:page]
    @tweet = Tweet.new
  end
  
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController

  before_action :set_tweet, only: [:show, :edit,:update,:destroy, :complete]
  
  def new
    @retweet= Retweet.new
  end
  
  def create
    tweet=Tweet.find_by(id:params[:format])
    if Retweet.find_by(user_id:current_user.id,tweet_id:tweet.id )
      @destruir= Retweet.find_by(user_id:current_user.id,tweet_id:tweet.id)
      @destruir.destroy
      tweet.retweets_count-=1
      tweet.save
      redirect_to root_path
    else
      Retweet.create(user_id:current_user.id, tweet_id:tweet.id)
      tweet.retweets_count+=1
      tweet.save
      redirect_to root_path
    end
  end

  def destroy
  end

private

  def retweet_params
    params.require(:retweet).permit(:user_id,:retweet_id)
  end
  
  def set_retweet
    @retweet = Retweet.find(params[:id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_current_tweet, only: [:likes, :retweet]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    organized_pages
    @tweet= Tweet.new
    @retweets= Retweet.all 
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @likes = Like.all 
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  # def edit
  # end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        #format.html { redirect_to @tweet, notice: 'El tweet se creó correctamente.' }
        format.html { redirect_to root_path, notice: 'El tweet se creó correctamente.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def likes
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)

    else
      @tweet.add_like(current_user)

    end 
    redirect_to root_path
  end

  def retweet
    new_tweet = Tweet.create(content: @tweet.content, user: current_user, rt_ref:@tweet.id)
    redirect_to root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user)
    end
  
  def organized_pages
    @tweets = Tweet.order(:created_at).page params[:page]
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HitoUno</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"> 
  </head>

  <body>
    <%=render 'shared/navbar' %>
  
    <div class="container">
      <% if notice %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Información</h4>
          <p><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Atención</h4>
          <p><%= alert %></p>
        </div>
    <% end %> 

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
    <div class="container">

        <a class="navbar-brand" href="<%=root_path%>">Tweeter</a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> 
            <span class="navbar-toggler-icon"></span> 
        </button> 
    <div class="collapse navbar-collapse" id="navbarNav"> 
        <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %> 
                <li class="nav-item active"> <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "nav-link"%> </li> 
            <% else %> 
                <li class="nav-item"> <%=link_to 'Iniciar Sesión',new_user_session_path, class: "nav-link" %></li> 
                <li class="nav-item"> <%= link_to 'Registrarse',new_user_registration_path, class: "nav-link" %></li> 
            <% end %> 
        </ul>
    </div> 
</nav>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content, "#{current_user.name} dice:" %>
    <%= form.text_area :content, id: :tweet_content, :class => "form-control" %>
  </div>
  <%# <div class="field">
    <%= form.label :user_id%>
    <%#= form.text_area :user_id, :class => "form-control" %>
  <%# #</div> %>

  <div class="actions text-right my-2">
    <%= form.submit "Guardar", :class => " btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<% if current_user %>  
  <%= render 'form', tweet: @tweet %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%=image_tag tweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
        <td><%= tweet.user.name %></td>
        <td><%= link_to time_ago_in_words(tweet.created_at) , tweet%></td> 
        <td><%= tweet.content %></td>
        <td><%= link_to 'Ver', tweet %></td>
        <td><%= link_to 'Editar', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Eliminar', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td>
          <%=tweet.likes_count%>
          <%= link_to 'like', likes_path(tweet.id), method: :post, class: "fas fa-heart"%>
        </td>

        <td>
          <%=tweet.retweets_count%>
          <%= link_to 'retweet', retweets_path(tweet.id), method: :post, class: "fas fa-retweet"%> 
        </td>
      </tr>
    <% end %>
  </tbody>

  <tbody>
    <% @retweets.each do |retweet| %>
    <tr>
      <td><%=image_tag retweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
      <td><%= retweet.user.name %></td>
      <td><%=image_tag retweet.tweet.user.image_url, class: "images_avatar rounded-circle border border-info " %></td>  
      <td><%= retweet.tweet.user.name %></td>
      <td><a href=<%=tweets_path(retweet.tweet_id)%>> <%= time_ago_in_words(retweet.tweet.created_at) %></a></td> 
      <td><%= retweet.tweet.content %></td>
    
      <td>
        <%=retweet.tweet.likes_count%>
        <%= link_to 'like', likes_path(retweet.tweet.id), method: :post, class: "fas fa-heart"%>
      </td>

      <td>
        <%=retweet.tweet.retweets_count%>
        <%= link_to 'retweet', retweets_path(retweet.tweet.id), method: :post, class: "fas fa-retweet"%> 
      </td>
    </tr>

  <% end %>

</tbody>

</table>

<br>

<%= link_to 'Nuevo Tweet', new_tweet_path %>
<%= paginate @tweets %>

app/views/tweets/new.html.erb
<h1>Nuevo Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class= "row">
  <div class= "col-12  shadow-lg rounded  p-1 mt-3 card">
    <div class="row">
              
      <div class="col-9 "> 
        <span class="username"><%= @tweet.user.name%> dice: </span></br/>   
        <span><%=link_to '<i class="far fa-calendar-alt"></i>'.html_safe+distance_of_time_in_words(Time.now, @tweet.created_at), @tweet%></span></br/>
        <%= @tweet.content%>
      </div>

      <div class= "col-12">

        <% @likes.each do |like| %>
          <% if @tweet.id==like.tweet_id %>

            <%=image_tag like.user.image_url, class: "images_avatar rounded-circle border border-info " %>

          <% end %>
        <% end %>

      </div>
    </div>
  </div>

</div>

<%= link_to 'Back', tweets_path %>